name: healthcare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.4.0
  http: 1.3.0
  shared_preferences: ^2.0.6
  google_sign_in: ^5.2.1
  cupertino_icons: ^1.0.8
  geolocator: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
